name: Upload Python Package

on:
  push:
    branches: ["stable"]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install py/build
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build binaries
        run: python -m build
      - name: Store distro packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  deploy:
    name: Publish distribution to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/vlrscraper
    permissions:
      id-token: write
    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_VLRSCRAPER_API_KEY }}
