name: Code Quality

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:

permissions:
  contents: read

jobs:
  name: lint
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python 11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov tox tox-gh-actions
        pip install -e .
    - name: Test with tox
      run: |
        tox -e lint
