name: Code Quality

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Run mypy, ruff and pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Lint with tox
        run: |
          tox -e lint
  format:
    name: Check code formatting with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Format with tox
        run: |
          tox -e ruff
