# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python code quality

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: python ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - 3.7
          - 3.8
          - 3.9
          - 3.11
          - 3.12
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov tox tox-gh-actions
        pip install -e .
    - name: Test with tox
      run: |
        tox
